# Generated by Django 4.1.7 on 2023-03-24 16:56

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemark',
            name='mark',
            field=models.FloatField(validators=[main.models.validate_mark]),
        ),
    ]
