# Generated by Django 4.1.7 on 2023-03-24 17:04

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_coursemark_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemark',
            name='mark',
            field=models.FloatField(null=True, validators=[main.models.validate_mark]),
        ),
    ]
