# Generated by Django 4.1.7 on 2023-03-30 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_coursemark_mark'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Class',
            new_name='Group',
        ),
        migrations.RenameModel(
            old_name='ClassCourse',
            new_name='GroupCourse',
        ),
        migrations.RenameField(
            model_name='classcoursestudent',
            old_name='class_course_id',
            new_name='group_course',
        ),
        migrations.RenameField(
            model_name='classcourseteacher',
            old_name='class_course_id',
            new_name='group_course',
        ),
        migrations.RenameField(
            model_name='groupcourse',
            old_name='class_id',
            new_name='group',
        ),
        migrations.AlterUniqueTogether(
            name='classcoursestudent',
            unique_together={('group_course', 'students')},
        ),
        migrations.AlterUniqueTogether(
            name='classcourseteacher',
            unique_together={('group_course', 'teacher')},
        ),
        migrations.AlterUniqueTogether(
            name='groupcourse',
            unique_together={('group', 'course')},
        ),
    ]
