# Generated by Django 4.1.7 on 2023-03-30 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_class_group_rename_classcourse_groupcourse_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClassCourseStudent',
            new_name='GroupCourseStudent',
        ),
        migrations.RenameModel(
            old_name='ClassCourseTeacher',
            new_name='GroupCourseTeacher',
        ),
    ]
