# Generated by Django 4.1.7 on 2023-03-30 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_classcoursestudent_groupcoursestudent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcourse',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.group'),
        ),
    ]
